### ISSUE TITLE
Difference between Pathway Analysis: GUI through Web vs POST

### ISSUE THREAD

**Issue by dvklopfenstein** [reactome/analysis-service#3]
FYI: I am seeing a difference between the results of pathway analyses done through the GUI on the web and the results run and downloaded from the API on the same data.

This analysis was done using the UniProt data downloaded from https://reactome.org/PathwayBrowser/#TOOL=AT

The inputs for both analyses are:
  * projection=true
  * interactors=false

For the run with the API, _includeDisease_= true. I am not sure how to set that for the GUI on the web.

![image](https://user-images.githubusercontent.com/7278188/55358830-56d6e280-549e-11e9-9c2e-0639e99e0e77.png)

**Comment by fabregat** [comment]
Dear Klopfenstein,

It seems you are downloading the results for "TOTAL" in the service API and for "UNIPROT" in the website. Could you please check that?

**Comment by dvklopfenstein** [comment]
You are correct. It matches perfectly when using TOTAL.

Thank you for the amazing tools.
